import { test, before } from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
// Use the same Admin SDK instance as the functions workspace (the repository
// also installs a separate copy for its rule tests).
const require = createRequire(new URL("../../functions/package.json", import.meta.url));
const { initializeApp, getApps } = require("firebase-admin/app");
const { getAuth } = require("firebase-admin/auth");
const { getFirestore } = require("firebase-admin/firestore");
import { createPlatformUser, updatePlatformUser, setPlatformUserSuspended, setPlatformUserPassword, getPlatformPasswordResetLink, listPlatformUsers } from "../../functions/platform/userAdmin.js";
import { setPricingPlans, setFamilySubscription } from "../../functions/platform/subscriptions.js";
import { DEFAULT_PLANS, consumePlanUsage, subscriptionRef, allowancePeriod, usageRef } from "../../functions/lib/subscriptions.js";
import { assertUserAccess } from "../../functions/lib/caller.js";
import { requestPlanChange, reviewPlanRequest, ADMIN_EMAIL } from "../../functions/platform/planRequests.js";
import { getMySubscription, getSubscriptionAdmin } from "../../functions/platform/subscriptions.js";

const enabled = Boolean(process.env.FIRESTORE_EMULATOR_HOST && process.env.FIREBASE_AUTH_EMULATOR_HOST);
let adminRequest;
before(async () => {
  if (!enabled) return;
  if (!getApps().length) initializeApp({ projectId: "demo-subscriptions-test" });
  const admin = await getAuth().createUser({ email: `admin-${Date.now()}@example.test`, password: "Admin-test-123" });
  await getAuth().setCustomUserClaims(admin.uid, { platformRole: "superadmin" });
  adminRequest = { auth: { uid: admin.uid, token: { platformRole: "superadmin", auth_time: Math.ceil(Date.now() / 1000) + 5 } } };
});
test("manual subscriptions and account management through actual Auth/Firestore emulators", { skip: !enabled }, async () => {
  const db = getFirestore(), auth = getAuth();
  const request = (data) => ({ ...adminRequest, data });
  await assert.rejects(listPlatformUsers.run({ auth: { uid: "ordinary", token: {} }, data: {} }), { code: "permission-denied" });
  const password = "Initial-secret-123", changedPassword = "Changed-secret-456";
  const r = await createPlatformUser.run(request({ email: `member-${Date.now()}@example.test`, displayName: "Test member", password, familyName: "Subscription test family", platformRole: "superadmin" }));
  const { uid, familyId } = r.user;
  assert.equal((await auth.getUser(uid)).customClaims.platformRole, undefined);
  await assert.rejects(consumePlanUsage(db, familyId, "text", { uid }), { code: "failed-precondition" });
  const plans = structuredClone(DEFAULT_PLANS); plans.basic.limits.text = 3;
  await setPricingPlans.run(request({ plans }));
  const start = Date.now() - 60000;
  await setFamilySubscription.run(request({ familyId, planId: "basic", status: "active", startsAt: start, endsAt: start + 30 * 86400000, paymentStatus: "paid", paymentReference: "CASH-TEST", notes: "Paid outside app" }));
  assert.equal((await subscriptionRef(db, familyId).get()).data().agreedPrice, 4500);
  const reservations = await Promise.allSettled(Array.from({ length: 8 }, () => consumePlanUsage(db, familyId, "text", { uid })));
  const passed = reservations.filter((s) => s.status === "fulfilled").length;
  assert.ok(passed > 0 && passed <= 3);
  const sub = (await subscriptionRef(db, familyId).get()).data();
  assert.equal((await usageRef(db, familyId, allowancePeriod(sub)).get()).data().text, passed);
  await updatePlatformUser.run(request({ uid, email: `renamed-${Date.now()}@example.test`, displayName: "Renamed member" }));
  assert.equal((await auth.getUser(uid)).displayName, "Renamed member");
  assert.equal((await db.collection("families").doc(familyId).collection("members").doc(uid).get()).data().displayName, "Renamed member");
  await setPlatformUserSuspended.run(request({ uid, disabled: true }));
  assert.equal((await auth.getUser(uid)).disabled, true);
  await assert.rejects(assertUserAccess({ auth: { uid, token: { auth_time: Math.ceil(Date.now() / 1000) + 5 } } }, db), { code: "permission-denied" });
  await assert.rejects(consumePlanUsage(db, familyId, "image", { uid }), { code: "permission-denied" });
  await setPlatformUserSuspended.run(request({ uid, disabled: false }));
  assert.equal((await auth.getUser(uid)).disabled, false);
  const reset = await getPlatformPasswordResetLink.run(request({ uid }));
  assert.ok(reset.link.includes("oobCode="));
  await setPlatformUserPassword.run(request({ uid, password: changedPassword }));
  await assert.rejects(assertUserAccess({ auth: { uid, token: { auth_time: Math.floor(start / 1000) } } }, db), { code: "unauthenticated" });
  await assert.rejects(setPlatformUserSuspended.run(request({ uid: adminRequest.auth.uid, disabled: true })), { code: "failed-precondition" });
  const users = (await listPlatformUsers.run(request({}))).users;
  assert.ok(users.some((u) => u.uid === uid && !u.disabled && u.familyId === familyId));
  const persisted = JSON.stringify({ user: (await db.collection("users").doc(uid).get()).data(), audit: (await db.collection("platformAudit").get()).docs.map((d) => d.data()) });
  assert.equal(persisted.includes(password), false); assert.equal(persisted.includes(changedPassword), false); assert.equal(persisted.includes(reset.link), false);
});

test("package requests require review, preserve quotes and atomically activate only after approval", { skip: !enabled }, async () => {
  const db = getFirestore();
  const admin = (data) => ({ ...adminRequest, data });
  const user = (await createPlatformUser.run(admin({ email: `requester-${Date.now()}@example.test`, displayName: "Requesting parent", password: "Initial-pass-123", familyName: "Request family" }))).user;
  const caller = (data) => ({ auth: { uid: user.uid, token: { email: user.email, auth_time: Math.ceil(Date.now() / 1000) + 10 } }, data });
  await assert.rejects(requestPlanChange.run(caller({ planId: "free" })), { code: "invalid-argument" });
  const results = await Promise.allSettled([requestPlanChange.run(caller({ planId: "premium", price: 1, familyId: "other", to: "attacker@example.test" })), requestPlanChange.run(caller({ planId: "basic" }))]);
  assert.equal(results.filter((r) => r.status === "fulfilled").length, 1);
  assert.equal(results.find((r) => r.status === "rejected").reason.code, "already-exists");
  const pending = results.find((r) => r.status === "fulfilled").value.request;
  assert.ok(pending.price >= 4500);
  assert.equal((await getMySubscription.run(caller({}))).subscription.effectiveStatus, "pending");
  const email = (await db.collection("mail").doc(pending.id).get()).data();
  assert.deepEqual(email.to, [ADMIN_EMAIL]);
  assert.equal(email.requestId, pending.id);
  assert.ok(email.message.text.includes("/platform"));
  const queue = (await getSubscriptionAdmin.run(admin({}))).requests;
  assert.ok(queue.some((r) => r.id === pending.id && r.familyId === user.familyId));
  await assert.rejects(reviewPlanRequest.run(caller({ requestId: pending.id, decision: "approve", paymentConfirmed: true })), { code: "permission-denied" });
  await assert.rejects(reviewPlanRequest.run(admin({ requestId: pending.id, decision: "approve" })), { code: "failed-precondition" });
  const plans = structuredClone(DEFAULT_PLANS); plans[pending.planId].price = 19000;
  await setPricingPlans.run(admin({ plans }));
  const approvals = await Promise.allSettled([1, 2].map(() => reviewPlanRequest.run(admin({ requestId: pending.id, decision: "approve", paymentConfirmed: true, paymentReference: "CASH-REQUEST" }))));
  assert.equal(approvals.filter((r) => r.status === "fulfilled").length, 1);
  assert.equal(approvals.find((r) => r.status === "rejected").reason.code, "failed-precondition");
  const sub = (await subscriptionRef(db, user.familyId).get()).data();
  assert.equal(sub.planId, pending.planId); assert.equal(sub.agreedPrice, pending.price); assert.equal(sub.paymentStatus, "paid");
  assert.equal(sub.endsAt.toMillis() - sub.startsAt.toMillis(), pending.durationDays * 86400000);
  await assert.rejects(requestPlanChange.run(caller({ planId: pending.planId })), { code: "failed-precondition" });
  const rejected = await requestPlanChange.run(caller({ planId: pending.planId === "premium" ? "basic" : "premium" }));
  await reviewPlanRequest.run(admin({ requestId: rejected.request.id, decision: "reject", reason: "Payment pending" }));
  assert.equal((await subscriptionRef(db, user.familyId).get()).data().planId, sub.planId);
  assert.equal((await getMySubscription.run(caller({}))).planRequest.rejectionReason, "Payment pending");
});
