<script setup>
import { ref, computed, onMounted } from "vue";
import { getMySubscription, requestPlanChange } from "@/services/admin";
import { learningAllowances, learningFeatures, packageDescriptions, packageStates } from "@/lib/packageCopy";
const data = ref(null), error = ref(""), loading = ref(false), submitting = ref(false), message = ref("");
const labels = Object.fromEntries(Object.entries(learningAllowances).map(([id, value]) => [id, value.label]));
const plan = computed(() => data.value?.plans[data.value.subscription.planId]);
async function load() { loading.value = true; error.value = ""; try { data.value = await getMySubscription(); } catch (e) { error.value = e.message; } finally { loading.value = false; } }
onMounted(load);
async function choose(planId) {
  submitting.value = true; error.value = ""; message.value = "";
  try { const r = await requestPlanChange(planId); data.value.planRequest = r.request; message.value = "Request submitted. Arrange payment with the administrator; your package changes after approval."; }
  catch (e) { error.value = e.message; } finally { submitting.value = false; }
}
</script>
<template>
  <section><div class="head"><div><p class="eyebrow">YOUR FAMILY'S LEARNING JOURNEY</p><h1>Choose your family's learning package</h1><p class="intro">A curriculum, learning activities, a family planner, and support as your child grows. Choose the collection of ready-to-use learning activities that fits your family.</p></div><button class="btn" :disabled="loading" @click="load">Refresh</button></div><p v-if="error" role="alert" class="error">{{ error }}</p>
    <template v-if="data">
      <p v-if="message" role="status">{{ message }}</p>
      <article v-if="data.planRequest" class="card"><h2>Package request · {{ data.planRequest.status }}</h2><p>{{ data.planRequest.planName }} — {{ data.planRequest.currency }} {{ data.planRequest.price.toLocaleString() }}</p><p v-if="data.planRequest.status === 'pending'">Awaiting superadmin review. Your current package stays unchanged until approval.</p><p v-if="data.planRequest.rejectionReason">{{ data.planRequest.rejectionReason }}</p></article>
      <article class="card current-package"><p class="eyebrow">YOUR CURRENT PACKAGE</p><h2>{{ data.subscription.effectiveStatus === 'pending' ? 'Choose a package to begin' : plan?.name }} <span class="package-state">{{ packageStates[data.subscription.effectiveStatus] || data.subscription.effectiveStatus }}</span></h2><p v-if="data.subscription.effectiveStatus !== 'active'">Choose a learning package below, arrange payment with the administrator, and start after approval. The trial is a paid introduction; every package requires activation.</p><p v-else>Your family's learning package is active until {{ new Date(data.subscription.endsAt).toLocaleString() }}.</p><p v-if="data.subscription.agreedPrice">Agreed price: {{ data.subscription.currency }} {{ data.subscription.agreedPrice.toLocaleString() }} · payment {{ data.subscription.paymentStatus }}</p>
        <div v-if="data.subscription.effectiveStatus !== 'pending'" class="activity-usage"><strong>{{ data.usage.activities || 0 }} / {{ plan?.limits.activities }} activities prepared</strong><p>New or refreshed activities in this package. Reuse saved activities for more practice.</p></div><details v-if="data.subscription.effectiveStatus !== 'pending'"><summary>Package limits and supporting allowances</summary><div class="allowance-table"><table><thead><tr><th>Learning support</th><th>Used / package allowance</th><th>Per day</th></tr></thead><tbody><tr v-for="(label, kind) in labels" :key="kind"><td>{{ label }}<small>{{ learningAllowances[kind].description }}</small></td><td>{{ data.usage[kind] || 0 }} / {{ plan?.limits[kind] }}</td><td>{{ plan?.daily[kind] }}</td></tr></tbody></table></div></details>
      </article>
      <div class="plans"><article v-for="(p, id) in data.plans" :key="id" class="card plan-card"><p class="eyebrow">{{ packageDescriptions[id]?.eyebrow }}</p><h2>{{ p.name }}</h2><p class="package-description">{{ packageDescriptions[id]?.description }}</p><div class="price"><strong>{{ p.currency }} {{ p.price.toLocaleString() }}</strong><span>for {{ p.durationDays }} day{{ p.durationDays === 1 ? '' : 's' }}</span></div><div class="activity-offer"><strong>Up to {{ p.limits.activities }}</strong><span>ready-to-use learning activities</span><small>New or refreshed, across your family, during this package.</small></div><ul class="package-benefits"><li>Learning content: exercises, stories, reading and practice</li><li>Clear parent guidance and worked examples</li><li>Illustrations where they support the activity</li><li>Personal curriculum, planner and progress tracking</li><li>Reuse saved activities for extra practice</li></ul><details><summary>What's included and how it works</summary><p class="allowance-explanation">{{ learningAllowances.activities.description }} Up to {{ p.daily.activities }} can be prepared per day, within your package total. A syllabus is a collection of activities; its size depends on your subjects and remaining allowance.</p><p class="allowance-explanation">Optional support: up to {{ p.limits.tts }} read-aloud recordings and {{ p.limits.liveMinutes }} learning companion minutes, with {{ p.sessionMinutes }} minutes per conversation.</p><p class="allowance-explanation">Supporting preparation limits: {{ p.limits.text }} requests and {{ p.limits.image }} illustration requests per package. Complex preparations and retries use these limits; contact the administrator if they prevent you from preparing your activities.</p></details><button class="btn primary" :disabled="submitting || loading || data.planRequest?.status === 'pending' || (data.subscription.effectiveStatus === 'active' && data.subscription.planId === id)" @click="choose(id)">{{ data.subscription.effectiveStatus === 'active' && data.subscription.planId === id ? 'Current package' : 'Request this package' }}</button></article></div>
      <div class="learning-included"><h2>A complete learning workspace, in every package</h2><p>Packages include access to the same learning tools. Duration and learning allowances differ.</p><div class="feature-grid"><article v-for="feature in learningFeatures" :key="feature.title"><h3>{{ feature.title }}</h3><p>{{ feature.description }}</p></article></div></div>
      <article class="card package-faq"><h2>Know exactly what you're choosing</h2><p><strong>What counts as an activity?</strong> One prepared item with learning content, such as a maths exercise, story, reading task or language practice. A successful refresh or a set of child-specific versions of that activity uses one activity allowance. Failed preparation does not use an activity allowance; supporting request limits still apply.</p><p><strong>How many courses or sessions?</strong> Activities are organized into your syllabus and planner. They are not fixed-length courses or teacher-led classes. You choose how to use them with your child.</p><p><strong>Shared across your family:</strong> The activity total covers all children and subjects together. Reusing saved content does not prepare a new activity.</p><p><strong>Payment and renewal:</strong> Request a package, arrange payment outside the app, then start after administrator approval. Approval or renewal starts a new allowance. Daily limits reset at midnight UTC.</p></article>
    </template>
  </section>
</template>
<style scoped>
.head{display:flex;align-items:center;justify-content:space-between}.plans{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin:1.5rem 0}.card{padding:1.25rem;border:1px solid #d8dee8;border-radius:12px;background:#fff}.card h2{margin-top:0}table{width:100%;border-collapse:collapse}td,th{padding:.6rem;text-align:left;border-bottom:1px solid #e8edf4}.error{color:#b91c1c}li{margin:.5rem 0}@media(max-width:750px){.plans{grid-template-columns:1fr}}
</style>
<style scoped>
.head>.btn { padding:.65rem 1rem; background:white; color:#746080; border:1px solid #e5dced; border-radius:8px; cursor:pointer; font:inherit; font-size:.8rem; }.head>.btn:disabled { opacity:.5; cursor:wait; }
</style>
<style scoped>
.head { align-items:flex-start; gap:1.5rem; margin-bottom:2rem; }.head h1 { font-size:2rem; letter-spacing:-.7px; margin:0; max-width:650px; }.eyebrow { font-size:.7rem; letter-spacing:1.2px; font-weight:700; color:#88739e; margin:0 0 .8rem; }.intro { color:#6b6578; line-height:1.7; max-width:700px; }.current-package { margin-top:1.5rem; }.package-state { display:inline-block; font-size:.75rem; border-radius:999px; background:#f0eafa; padding:.4rem .7rem; margin-left:.5rem; vertical-align:middle; }.learning-included { margin:2.5rem 0 1.8rem; }.learning-included>h2 { font-size:1.3rem; }.learning-included>p { color:#71677e; font-size:.9rem; }.feature-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:1rem; margin-top:1.5rem; }.feature-grid article { border-left:3px solid #ddcaef; padding:.2rem 1rem; }.feature-grid h3 { font-size:.95rem; margin:.3rem 0; }.feature-grid p { color:#71677e; font-size:.85rem; line-height:1.65; margin:.5rem 0; }.plan-card { display:flex; flex-direction:column; }.package-description { color:#71677e; font-size:.9rem; line-height:1.6; min-height:80px; }.price strong { display:block; font-size:1.7rem; letter-spacing:-.6px; }.price span { display:block; color:#8a7c96; font-size:.85rem; margin-top:.5rem; }.tools-included { color:#8a699f; background:#faf6ff; font-size:.78rem; padding:.8rem; border-radius:8px; line-height:1.7; margin:1.5rem 0 .6rem; }.plan-card ul { padding-left:1.2rem; font-size:.85rem; line-height:1.5; }.plan-card details { font-size:.8rem; margin:1rem 0; }.plan-card .btn { margin-top:auto; padding:.7rem; border-radius:8px; border:0; cursor:pointer; }.plan-card details+.btn { margin-top:1rem; }.allowance-explanation { color:#71677e; line-height:1.7; font-size:.8rem; }.package-faq { margin-top:2rem; }.package-faq h2 { font-size:1.25rem; }.package-faq p { color:#71677e; font-size:.85rem; line-height:1.8; }summary { cursor:pointer; color:#805c9b; line-height:1.5; }table small { display:block; font-size:.75rem; line-height:1.6; color:#80748b; margin-top:.4rem; }.allowance-table { overflow:auto; }table { min-width:500px; }.current-package details { margin-top:1.4rem; }@media(max-width:750px){.feature-grid{grid-template-columns:1fr}.package-description{min-height:0}.head h1{font-size:1.6rem}.head{flex-wrap:wrap}.package-state{margin:.6rem 0 0}}
</style>


<style scoped>
.activity-offer{background:#f6f0ff;border-radius:12px;padding:1.2rem;margin:1.5rem 0 .7rem}.activity-offer strong{display:block;font-size:2rem;letter-spacing:-1px}.activity-offer span{display:block;font-weight:600;margin:.25rem 0}.activity-offer small{display:block;color:#71677e;font-size:.75rem;line-height:1.5;margin-top:.6rem}.activity-usage{background:#f6f0ff;padding:1rem;border-radius:10px;margin:1rem 0}.activity-usage p{font-size:.85rem;color:#71677e;margin:.5rem 0 0}.package-benefits{margin-bottom:auto}
</style>
