import { test } from "node:test";
import assert from "node:assert/strict";
import { generateContentForActivity, describeNoContent, looksLikeComputationProblem, hasEnoughComputationProblems } from "../agents/activityContent.js";

// A scripted fake LLM: returns the given responses in order, recording the
// generationConfig each call received so we can assert on the retry budget.
function scriptedLlm(responses) {
  let i = 0;
  const calls = [];
  return {
    calls,
    async generate(req) { calls.push(req); return responses[Math.min(i++, responses.length - 1)]; },
  };
}

const MATH = { id: "a1", title: "Addition within 10", type: "mathematics" };
const saveCall = (args) => ({ functionCalls: [{ name: "save_content", args }] });
const PROBLEMS = { kind: "problems", problems: [{ question: "2+3", answer: "5" }] };

const opts = { db: null, geminiApiKey: "", storagePrefix: "" }; // no DB / image side-effects

test("returns content on a clean save_content call (no retry)", async () => {
  const llm = scriptedLlm([saveCall(PROBLEMS), { text: "done" }]);
  const { content, reason } = await generateContentForActivity({ activity: MATH, llm, genConfig: { maxOutputTokens: 4096 }, ...opts });
  assert.ok(content, "content should be produced");
  assert.equal(content.problems[0].answer, "5");
  assert.equal(reason, "");
  // stopAfterTool ends the loop the instant save_content fires — no redundant
  // follow-up generate call (the old behavior asked the model again needlessly).
  assert.equal(llm.calls.length, 1);
});

// The activity docs need to know which provider/model wrote the content (so the
// UI can show "generated by Claude Sonnet 5" etc.) — derived from the llm client
// that actually ran, not a separately-tracked variable, so it can't drift.
test("returns the provider/model derived from the llm client that ran", async () => {
  const llm = scriptedLlm([saveCall(PROBLEMS), { text: "done" }]);
  llm.model = "claude-sonnet-5";
  const { provider, model } = await generateContentForActivity({ activity: MATH, llm, genConfig: { maxOutputTokens: 4096 }, ...opts });
  assert.equal(provider, "anthropic");
  assert.equal(model, "claude-sonnet-5");
});

test("returns an empty provider/model when the llm client carries no model id", async () => {
  const llm = scriptedLlm([saveCall(PROBLEMS), { text: "done" }]);
  const { provider, model } = await generateContentForActivity({ activity: MATH, llm, genConfig: { maxOutputTokens: 4096 }, ...opts });
  assert.equal(provider, "");
  assert.equal(model, "");
});

test("retries once on MAX_TOKENS, succeeds, and raises the output budget on retry", async () => {
  const llm = scriptedLlm([
    { text: "partial", finishReason: "MAX_TOKENS" },      // attempt 1: truncated → no tool call
    saveCall(PROBLEMS), { text: "done" },                  // attempt 2: succeeds
  ]);
  const { content, reason } = await generateContentForActivity({ activity: MATH, llm, genConfig: { maxOutputTokens: 4096 }, ...opts });
  assert.ok(content, "retry should recover content");
  assert.equal(reason, "");
  // The retry must use a larger budget than the first attempt (truncation fix).
  assert.equal(llm.calls[0].config.maxOutputTokens, 4096);
  assert.equal(llm.calls[1].config.maxOutputTokens, 8192);
});

test("reports a truncation reason when both attempts run out of space", async () => {
  const llm = scriptedLlm([{ text: "", finishReason: "MAX_TOKENS" }, { text: "", finishReason: "MAX_TOKENS" }]);
  const { content, reason } = await generateContentForActivity({ activity: MATH, llm, genConfig: { maxOutputTokens: 4096 }, ...opts });
  assert.equal(content, null);
  assert.match(reason, /ran out of output space/i);
});

test("reports a 'no save_content' reason when the model just chats", async () => {
  const llm = scriptedLlm([{ text: "Here is some prose." }, { text: "Still prose." }]);
  const { content, reason } = await generateContentForActivity({ activity: MATH, llm, genConfig: { maxOutputTokens: 4096 }, ...opts });
  assert.equal(content, null);
  assert.match(reason, /without calling save_content/i);
});

test("a hollow forced save_content call is retried, then reported as an empty payload", async () => {
  // Forced function calling guarantees the *call* fires; the failure mode now is
  // an empty payload. Both attempts return a shell → null content + clear reason.
  const EMPTY = { kind: "problems", problems: [] };
  const llm = scriptedLlm([saveCall(EMPTY), saveCall(EMPTY)]);
  const { content, reason } = await generateContentForActivity({ activity: MATH, llm, genConfig: { maxOutputTokens: 4096 }, ...opts });
  assert.equal(content, null);
  assert.match(reason, /payload was empty/i);
  assert.equal(llm.calls.length, 2); // first attempt + one retry
});

test("a teaching activity embeds a ready-to-use story in its tips content", async () => {
  // The core fix: parent-led (teaching → tips) activities that revolve around a
  // story must carry the FULL story, not tell the parent to go find one.
  const STORY_ACTIVITY = { id: "t1", title: "Empathy Story: Walking in Their Shoes", type: "teaching" };
  const TIPS = {
    kind: "tips",
    tips: {
      lang: "ur",
      story: { title: "ابو بکرؓ کی مہربانی", paragraphs: ["پہلا حصہ۔", "دوسرا حصہ۔", "آخری حصہ۔"], moral: "ہمدردی۔" },
      discussionQuestions: ["بچے نے کیسا محسوس کیا؟", "ہم کیا سیکھتے ہیں؟"],
      tips: ["کہانی آہستہ پڑھیں۔"],
    },
  };
  const llm = scriptedLlm([saveCall(TIPS), { text: "done" }]);
  const { content, reason } = await generateContentForActivity({ activity: STORY_ACTIVITY, llm, genConfig: { maxOutputTokens: 4096 }, ...opts });
  assert.equal(reason, "");
  assert.ok(content, "tips content should be produced");
  assert.equal(content.kind, "tips");
  assert.equal(content.tips.story.paragraphs.length, 3, "the full story is embedded");
  assert.equal(content.tips.story.moral, "ہمدردی۔");
  assert.equal(content.tips.discussionQuestions.length, 2);
  assert.equal(content.tips.lang, "ur");
});

test("a story-only tips payload (no facilitation tips) is still valid content", async () => {
  // isContentEmpty must treat an embedded story as content even when the bare
  // `tips` list is empty — the story is the deliverable.
  const STORY_ONLY = {
    kind: "tips",
    tips: { story: { paragraphs: ["A complete little story."], moral: "Kindness." } },
  };
  const llm = scriptedLlm([saveCall(STORY_ONLY), { text: "done" }]);
  const { content, reason } = await generateContentForActivity({ activity: { id: "t2", title: "Kindness tale", type: "teaching" }, llm, genConfig: { maxOutputTokens: 4096 }, ...opts });
  assert.equal(reason, "");
  assert.ok(content, "a story-only tips payload is not empty");
  assert.equal(content.tips.story.paragraphs.length, 1);
});

test("parent guidance is injected into the generation prompt", async () => {
  const llm = scriptedLlm([saveCall(PROBLEMS), { text: "done" }]);
  await generateContentForActivity({
    activity: MATH, llm, genConfig: { maxOutputTokens: 4096 }, ...opts,
    guidance: "The previous version was far too hard — use numbers under 5 only.",
  });
  // The system prompt the LLM received must carry the parent's instructions so
  // the model knows why it's regenerating and what to change.
  assert.match(llm.calls[0].system, /PARENT'S INSTRUCTIONS FOR THIS REGENERATION/);
  assert.match(llm.calls[0].system, /numbers under 5 only/);
});

test("omitted guidance leaves no guidance block in the prompt", async () => {
  const llm = scriptedLlm([saveCall(PROBLEMS), { text: "done" }]);
  await generateContentForActivity({ activity: MATH, llm, genConfig: { maxOutputTokens: 4096 }, ...opts });
  assert.doesNotMatch(llm.calls[0].system, /PARENT'S INSTRUCTIONS FOR THIS REGENERATION/);
});

test("describeNoContent maps every stop reason to a clear message", () => {
  assert.match(describeNoContent({ stoppedAt: "truncated" }, "problems"), /output space.*\(problems\)/i);
  assert.match(describeNoContent({ stoppedAt: "blocked", blockReason: "SAFETY" }), /filtered \(SAFETY\)/);
  assert.match(describeNoContent({ stoppedAt: "limit" }), /step budget/i);
  assert.match(describeNoContent({ stoppedAt: "final" }), /without calling save_content/i);
});

// ─── Math "problems" quality guard ─────────────────────────────────────────────
// Regression coverage for the exact failure observed on a live activity: the
// model produced recognition/multiple-choice questions ("(1/2 ya 1/4?)")
// instead of calculations, despite the prompt already asking for real sums.

test("looksLikeComputationProblem accepts plain arithmetic and worded calculations", () => {
  assert.ok(looksLikeComputationProblem("7 + 5 = ?"));
  assert.ok(looksLikeComputationProblem("1/2 + 1/4 = ?"));
  assert.ok(looksLikeComputationProblem("Ali has 7 apples and buys 5 more. How many apples does he have now?"));
});

test("looksLikeComputationProblem rejects recognition/multiple-choice questions", () => {
  // The exact real-world failure: a fraction-identification question with a
  // parenthetical either/or, in roman-Urdu ("ya" = "or").
  assert.equal(looksLikeComputationProblem("Har hissa poori roti ka kitna hissa hai? (1/2 ya 1/4?)"), false);
  assert.equal(looksLikeComputationProblem("Which is bigger (3 or 5?)"), false);
});

test("looksLikeComputationProblem rejects questions with fewer than two numbers", () => {
  assert.equal(looksLikeComputationProblem("What is half of a pizza?"), false);
  assert.equal(looksLikeComputationProblem(""), false);
});

test("hasEnoughComputationProblems passes non-problems content and a majority-good problem set", () => {
  assert.equal(hasEnoughComputationProblems({ kind: "tips", tips: { tips: ["x"] } }), true);
  assert.equal(hasEnoughComputationProblems({
    kind: "problems",
    problems: [{ question: "7 + 5 = ?" }, { question: "13 - 6 = ?" }, { question: "(1/2 ya 1/4?)" }],
  }), true); // 2 of 3 pass
});

test("hasEnoughComputationProblems fails a majority-recognition-question set", () => {
  assert.equal(hasEnoughComputationProblems({
    kind: "problems",
    problems: [{ question: "(1/2 ya 1/4?)" }, { question: "Which is bigger (3 or 5?)" }, { question: "7 + 5 = ?" }],
  }), false); // only 1 of 3 pass
});

test("generateContentForActivity retries a majority-recognition math set and accepts a good retry", async () => {
  const BAD_PROBLEMS = {
    kind: "problems",
    problems: [
      { question: "Har hissa poori roti ka kitna hissa hai? (1/2 ya 1/4?)", answer: "1/2" },
      { question: "Which is bigger (3 or 5?)", answer: "5" },
    ],
  };
  const GOOD_PROBLEMS = { kind: "problems", problems: [{ question: "1/2 + 1/4 = ?", answer: "3/4" }] };
  const llm = scriptedLlm([saveCall(BAD_PROBLEMS), saveCall(GOOD_PROBLEMS), { text: "done" }]);
  const { content, reason } = await generateContentForActivity({ activity: MATH, llm, genConfig: { maxOutputTokens: 4096 }, ...opts });
  assert.equal(reason, "");
  assert.equal(content.problems[0].question, "1/2 + 1/4 = ?");
  assert.equal(llm.calls.length, 2);
  // The retry's nudge must name the exact failure so the model doesn't repeat it.
  assert.match(llm.calls[1].contents[0].parts[0].text, /pick\/identify a pre-stated option/);
});

test("generateContentForActivity accepts a still-imperfect retry rather than returning no content", async () => {
  const BAD_PROBLEMS = {
    kind: "problems",
    problems: [
      { question: "(1/2 ya 1/4?)", answer: "1/2" },
      { question: "Which is bigger (3 or 5?)", answer: "5" },
    ],
  };
  const llm = scriptedLlm([saveCall(BAD_PROBLEMS), saveCall(BAD_PROBLEMS), { text: "done" }]);
  const { content, reason } = await generateContentForActivity({ activity: MATH, llm, genConfig: { maxOutputTokens: 4096 }, ...opts });
  assert.ok(content, "a degraded-but-real activity beats no content at all");
  assert.equal(reason, "");
  assert.equal(llm.calls.length, 2); // only ever retries once
});
